<?php

namespace App\Console\Commands;

use App\Models\User;
use App\Services\NotificationScanner;
use App\Support\NotificationCategories;
use Illuminate\Console\Command;

/**
 * Give one user a cleaner notification slate, then re-run the live scanner so current preventive
 * conditions are correctly indexed. Defaults to the Inspector, Abu Maroof (abomarof@faster.local).
 *
 * Two modes:
 *   (default)  Wipe EVERYTHING for the user, then re-scan. Simple but one-way for event-driven alerts.
 *   --safe     Preserve the user's ACTIVE-WORKFLOW rows (complaints + test-drive hand-offs) and purge
 *              only the debris: rows in the catch-all "Other" tab, plus any row the current role-gate no
 *              longer permits this user to see (legacy rows written before the gate existed). Routine
 *              rows are kept and refreshed by the re-scan.
 *
 *   php artisan notifications:reset --safe          # Abu Maroof, targeted purge (asks to confirm)
 *   php artisan notifications:reset --safe --force  # no prompt
 *   php artisan notifications:reset 10              # full wipe of user 10
 */
class NotificationsReset extends Command
{
    protected $signature = 'notifications:reset
        {user=abomarof@faster.local : User id or email whose notifications to reset}
        {--safe : Preserve complaints + test-drive rows; purge only Other/role-gate-invalid debris}
        {--force : Skip the confirmation prompt}';

    protected $description = "Clear a user's stale notifications and repopulate current, live alerts";

    public function handle(NotificationScanner $scanner): int
    {
        $ref  = $this->argument('user');
        $user = is_numeric($ref)
            ? User::find($ref)
            : User::where('email', $ref)->first();

        if (! $user) {
            $this->error("No user found for '{$ref}'.");

            return self::FAILURE;
        }

        $all   = $user->notifications()->get();
        $count = $all->count();
        $safe  = (bool) $this->option('safe');

        $this->line("Target: <info>{$user->name}</info> <{$user->email}> — <comment>{$count}</comment> notification(s) on record.");

        // Decide which rows die. In --safe mode we filter in PHP (the set is tiny — one user's feed) so
        // the keep/purge rule can read each row's derived category + the role-gate together.
        if ($safe) {
            $denied   = NotificationScanner::deniedTypesFor($user);            // types this user may no longer receive
            $preserve = ['complaints', 'test_drive'];                          // active workflow — never touched
            $doomed   = $all->filter(function ($n) use ($denied, $preserve) {
                $type = $n->data['type'] ?? null;
                $cat  = NotificationCategories::categoryOf($type);
                if (in_array($cat, $preserve, true)) {
                    return false; // in-flight complaint / test-drive → keep
                }
                // Debris: the catch-all "Other" tab, or a row the role-gate now hides from this user.
                return $cat === NotificationCategories::OTHER || in_array($type, $denied, true);
            });

            $this->line('Mode: <info>SAFE</info> — complaints + test-drive rows are preserved.');
            $this->line("Will purge <comment>{$doomed->count()}</comment> debris row(s), keep <info>" . ($count - $doomed->count()) . '</info>.');
        } else {
            $this->warn('FULL WIPE — event-driven alerts (complaints, test-drive hand-offs) will NOT be regenerated by the re-scan; clearing them is permanent.');
        }

        if (! $this->option('force') && ! $this->confirm("Proceed for {$user->name}?", true)) {
            $this->line('Aborted — nothing was deleted.');

            return self::SUCCESS;
        }

        $deleted = $safe
            ? $user->notifications()->whereIn('id', $doomed->pluck('id'))->delete()
            : $user->notifications()->delete();
        $this->info("Deleted {$deleted} notification(s).");

        // Re-run the full live scan. Idempotent + per-user gated: it repopulates this user's active
        // routine conditions (and no-ops for everyone else who already holds theirs).
        $r = $scanner->scan();
        $after = $user->fresh()->notifications()->count();

        $this->info(sprintf(
            'Scan complete — %d live condition(s) fleet-wide, %d new raised. %s now holds %d notification(s).',
            $r['alerts'],
            $r['created'],
            $user->name,
            $after
        ));

        return self::SUCCESS;
    }
}
