<?php

/**
 * Engine fault concepts.
 *
 * ENGINE_MECH is 1,868 recorded events in this fleet and CHECK_ENGINE another 1,412 — mid-table by
 * volume, but the category with the highest cost per event, so the vocabulary depth is justified.
 *
 * Arabic here is deliberately Gulf/Levantine as spoken in this workshop ("الموتر", "المكينة",
 * "يحما"), not Modern Standard. The formal forms are present for written records; the spoken ones
 * are what the matcher will actually receive.
 */

return [
    [
        'name' => 'Overheating', 'name_ar' => 'ارتفاع حرارة المحرك',
        'category' => 'engine', 'category_label' => 'Engine', 'category_label_ar' => 'المحرك',
        'system' => 'Cooling system', 'subsystem' => 'Coolant circuit', 'discipline' => 'mechanical',
        'risk' => 'critical',
        'description' => 'Engine temperature above safe range — continuing to drive risks head-gasket and bearing damage.',
        'en' => [
            'syn'      => ['engine overheating', 'overheat', 'high engine temperature', 'temperature warning'],
            'workshop' => ['running hot', 'temp gauge in the red', 'boiling over', 'blowing coolant'],
            'customer' => ['engine running hot', 'temperature gauge going up', 'steam from the bonnet',
                           'steam from the hood', 'car is boiling', 'temp light came on', 'smoke from the engine'],
            'miss'     => ['over heating', 'overheatting', 'engin overheating', 'over heat'],
        ],
        'ar' => [
            'formal'   => ['ارتفاع حرارة المحرك', 'سخونة المحرك'],
            'workshop' => ['الموتر يسخن', 'السيارة تسخن', 'المكينة حامية', 'الموتر يحما',
                           'حرارة المكينة عالية', 'الحرارة تطلع', 'طلع بخار من المكينة'],
        ],
        'components' => ['Radiator', 'Water pump', 'Thermostat', 'Cooling fan', 'Coolant hoses', 'Head gasket'],
        'causes' => ['Coolant leak', 'Water-pump failure', 'Faulty thermostat', 'Radiator blockage / scaling',
                     'Cooling-fan not running', 'Blown head gasket', 'Low coolant level'],
        'inspection' => ['Check coolant level cold', 'Pressure-test the cooling system',
                         'Confirm fan runs at temperature', 'Check thermostat opening', 'Check for exhaust gas in coolant'],
        'actions' => ['replace_thermostat', 'replace_coolant', 'replace_water_pump', 'replace_radiator',
                      'replace_cooling_fan', 'replace_coolant_hose', 'clean_radiator', 'replace_head_gasket', 'road_test'],
    ],
    [
        'name' => 'Engine noise', 'name_ar' => 'صوت غير طبيعي من المحرك',
        'category' => 'engine', 'system' => 'Engine', 'subsystem' => 'Rotating assembly', 'discipline' => 'mechanical',
        'risk' => 'critical',
        'description' => 'Abnormal mechanical noise from the engine — knocking, ticking or rattling.',
        'en' => [
            'syn'      => ['abnormal engine noise', 'engine knocking', 'knocking sound', 'engine rattle', 'engine ticking'],
            'workshop' => ['bottom end knock', 'top end tick', 'noisy lifters', 'rod knock', 'timing chain rattle'],
            'customer' => ['strange sound from the engine', 'knocking sound', 'ticking noise',
                           'engine sounds rough', 'loud engine', 'rattling from the front', 'metallic noise from engine'],
            'miss'     => ['engin noise', 'nocking sound', 'engine nois'],
        ],
        'ar' => [
            'formal'   => ['صوت غير طبيعي من المحرك', 'طرق في المحرك'],
            'workshop' => ['صوت من المكينة', 'المكينة تطق', 'صوت غريب قدام', 'المكينة تخبط', 'فيه دقة بالمكينة'],
        ],
        'components' => ['Timing chain', 'Hydraulic lifters', 'Main bearings', 'Accessory belt', 'Pulleys'],
        'causes' => ['Low / degraded engine oil', 'Worn timing chain / tensioner', 'Faulty hydraulic lifters',
                     'Worn main / big-end bearings', 'Accessory belt / pulley wear'],
        'inspection' => ['Check oil level and condition', 'Locate noise with stethoscope',
                         'Check noise vs engine speed', 'Inspect belt and pulleys'],
        'actions' => ['replace_engine_oil', 'replace_oil_filter', 'replace_timing_chain',
                      'replace_accessory_belt', 'road_test', 'scan_diagnostics'],
    ],
    [
        'name' => 'Rough idle / misfire', 'name_ar' => 'عدم انتظام دوران المحرك',
        'category' => 'engine', 'system' => 'Engine', 'subsystem' => 'Ignition / fuel', 'discipline' => 'mechanical',
        'risk' => 'moderate',
        'description' => 'Engine runs unevenly at idle or misfires under load.',
        'en' => [
            'syn'      => ['misfire', 'rough idle', 'engine shaking', 'uneven idle', 'engine vibration at idle'],
            'workshop' => ['missing on a cylinder', 'running on three', 'shaking at idle', 'stumble'],
            'customer' => ['it hesitates', 'car shakes when stopped', 'engine stutters', 'jerking when driving',
                           'vibrates only when cold', 'shaking at traffic lights', 'car judders'],
            'miss'     => ['mis fire', 'missfire', 'ruff idle'],
        ],
        'ar' => [
            'formal'   => ['عدم انتظام دوران المحرك', 'ارتجاج المحرك'],
            'workshop' => ['الموتر يرجف وهو واقف', 'يقطع', 'يرجف على البارد', 'المكينة ترجف', 'فيه رجة'],
        ],
        'components' => ['Spark plugs', 'Ignition coils', 'Fuel injectors', 'Throttle body', 'Vacuum lines'],
        'causes' => ['Worn spark plugs / coils', 'Clogged / faulty fuel injector', 'Vacuum leak',
                     'Dirty throttle body', 'Faulty ignition coil'],
        'inspection' => ['Scan for misfire codes', 'Identify affected cylinder', 'Inspect plugs and coils',
                         'Check for vacuum leaks'],
        'actions' => ['replace_spark_plugs', 'replace_ignition_coil', 'clean_throttle_body',
                      'clean_fuel_injector', 'replace_fuel_injector', 'repair_vacuum_leak', 'scan_diagnostics', 'road_test'],
    ],
    [
        'name' => 'Loss of power', 'name_ar' => 'ضعف في قوة المحرك',
        'category' => 'engine', 'system' => 'Engine', 'subsystem' => 'Air / fuel delivery', 'discipline' => 'mechanical',
        'risk' => 'moderate',
        'description' => 'Engine does not deliver expected power, especially under load or uphill.',
        'en' => [
            'syn'      => ['power loss', 'weak acceleration', 'sluggish', 'no pull', 'poor performance', 'limp mode'],
            'workshop' => ['down on power', 'gone into limp', 'not making boost', 'flat on acceleration'],
            'customer' => ["it doesn't pull", 'no power going uphill', 'car feels slow', 'engine feels weak',
                           'not accelerating properly', 'car is very slow now'],
            'miss'     => ['loss of pwer', 'lose of power'],
        ],
        'ar' => [
            'formal'   => ['ضعف في قوة المحرك', 'انخفاض الأداء'],
            'workshop' => ['الموتر ما يسحب', 'ما فيه قوة', 'ضعيف في الطلعة', 'ثقيل ما يمشي', 'السيارة ما تسحب'],
        ],
        'components' => ['Air filter', 'Fuel filter', 'Fuel pump', 'Turbocharger', 'Catalytic converter', 'Oxygen sensor'],
        'causes' => ['Clogged air filter', 'Clogged fuel filter', 'Failing fuel pump',
                     'Blocked catalytic converter', 'Faulty oxygen sensor'],
        'inspection' => ['Scan for stored codes', 'Check air and fuel filters', 'Check fuel pressure', 'Road test under load'],
        'actions' => ['replace_air_filter', 'replace_fuel_filter', 'clean_fuel_injector',
                      'replace_oxygen_sensor', 'scan_diagnostics', 'road_test'],
    ],
    [
        'name' => 'Check-engine light', 'name_ar' => 'إضاءة لمبة فحص المحرك',
        'category' => 'engine', 'system' => 'Engine management', 'subsystem' => 'ECU / sensors', 'discipline' => 'electrical',
        'risk' => 'moderate',
        'description' => 'Engine management warning lamp is lit — a stored fault code exists.',
        'en' => [
            'syn'      => ['check engine light', 'engine warning light', 'MIL', 'malfunction indicator lamp', 'engine light on'],
            'workshop' => ['light is on', 'has a code stored', 'CEL on'],
            'customer' => ['warning light on the dashboard', 'engine light came on', 'yellow light on dash',
                           'orange engine sign', 'light shaped like an engine'],
            'miss'     => ['check engin light', 'chek engine light'],
            'abbr'     => ['CEL', 'MIL', 'ECU light'],
        ],
        'ar' => [
            'formal'   => ['إضاءة لمبة فحص المحرك', 'مؤشر عطل المحرك'],
            'workshop' => ['لمبة المكينة', 'إشارة صفراء في الطبلون', 'علامة المكينة طالعة', 'لمبة الفحص'],
        ],
        'components' => ['ECU', 'Oxygen sensor', 'MAF sensor', 'Catalytic converter', 'EVAP system'],
        'causes' => ['Faulty oxygen sensor', 'Loose fuel cap / EVAP leak', 'Misfire detected',
                     'Catalytic converter efficiency low', 'Faulty MAF sensor'],
        'inspection' => ['Read fault codes', 'Record freeze-frame data', 'Confirm fault reproduces', 'Clear and re-test'],
        'actions' => ['scan_diagnostics', 'replace_oxygen_sensor', 'reset_warning_light', 'road_test'],
    ],
    [
        'name' => 'Hard starting', 'name_ar' => 'صعوبة في تشغيل المحرك',
        'category' => 'engine', 'system' => 'Engine', 'subsystem' => 'Starting system', 'discipline' => 'mechanical',
        'risk' => 'moderate',
        'description' => 'Engine cranks but takes unusually long to start.',
        'en' => [
            'syn'      => ['difficult starting', 'long crank', 'slow to start', 'hard to start'],
            'workshop' => ['cranks a long time', 'needs a few tries', 'no start when cold'],
            'customer' => ['takes long to start', 'have to crank it many times', 'hard to start in the morning',
                           'engine takes time to start'],
            'miss'     => ['hard startting', 'hard staring'],
        ],
        'ar' => [
            'formal'   => ['صعوبة في تشغيل المحرك'],
            'workshop' => ['ما يشتغل بسرعة', 'يتعب في التشغيل', 'يبغى له وقت يشتغل', 'صعب يدور'],
        ],
        'components' => ['Battery', 'Starter motor', 'Fuel pump', 'Spark plugs', 'Glow plugs'],
        'causes' => ['Weak battery', 'Failing fuel pump', 'Worn spark plugs', 'Faulty crank sensor', 'Low fuel pressure'],
        'inspection' => ['Test battery and charging', 'Check fuel pressure at crank', 'Scan for codes', 'Inspect plugs'],
        'actions' => ['replace_battery', 'replace_spark_plugs', 'replace_fuel_filter', 'scan_diagnostics', 'test_battery'],
    ],
    [
        'name' => 'Stalling', 'name_ar' => 'توقف المحرك أثناء التشغيل',
        'category' => 'engine', 'system' => 'Engine', 'subsystem' => 'Fuel / idle control', 'discipline' => 'mechanical',
        'risk' => 'critical',
        'description' => 'Engine cuts out while running — dangerous in traffic because steering and brake assist are lost.',
        'en' => [
            'syn'      => ['engine stalls', 'engine cuts out', 'engine dies', 'shuts off while driving'],
            'workshop' => ['dies at idle', 'cuts out under load', 'stalls when hot'],
            'customer' => ['engine cuts out', 'car switches off while driving', 'it dies at the lights',
                           'engine stops suddenly', 'car turns off by itself'],
            'miss'     => ['stalling engine', 'staling'],
        ],
        'ar' => [
            'formal'   => ['توقف المحرك أثناء التشغيل'],
            'workshop' => ['الموتر يطفي', 'يفصل وهو ماشي', 'يطفي على الإشارة', 'يموت وهو ماشي'],
        ],
        'components' => ['Idle air control', 'Fuel pump', 'Crank sensor', 'Throttle body', 'Ignition system'],
        'causes' => ['Failing fuel pump', 'Faulty crank / cam sensor', 'Dirty throttle body',
                     'Vacuum leak', 'Faulty idle control'],
        'inspection' => ['Scan for codes during fault', 'Check fuel pressure', 'Check sensor signal', 'Road test to reproduce'],
        'actions' => ['clean_throttle_body', 'replace_fuel_filter', 'repair_vacuum_leak', 'scan_diagnostics', 'road_test'],
    ],
    [
        'name' => 'Excessive exhaust smoke', 'name_ar' => 'دخان كثيف من العادم',
        'category' => 'engine', 'system' => 'Engine', 'subsystem' => 'Combustion / exhaust', 'discipline' => 'mechanical',
        'risk' => 'moderate',
        'description' => 'Visible smoke from the exhaust — colour indicates oil, coolant or fuel.',
        'en' => [
            'syn'      => ['exhaust smoke', 'blue smoke', 'white smoke', 'black smoke', 'smoking exhaust'],
            'workshop' => ['burning oil', 'blowing smoke', 'smoking on start-up'],
            'customer' => ['smoke from the exhaust', 'white smoke from the back', 'black smoke when accelerating',
                           'car is smoking'],
            'miss'     => ['exhust smoke', 'excesive smoke'],
        ],
        'ar' => [
            'formal'   => ['دخان كثيف من العادم'],
            'workshop' => ['دخان من الشكمان', 'يطلع دخان أبيض', 'دخان أسود', 'الشكمان يدخن'],
        ],
        'components' => ['Piston rings', 'Valve stem seals', 'Turbocharger', 'Head gasket', 'Injectors'],
        'causes' => ['Worn piston rings', 'Failed valve stem seals', 'Blown head gasket', 'Over-fuelling injector'],
        'inspection' => ['Note smoke colour and timing', 'Compression test', 'Check oil consumption', 'Check coolant loss'],
        'actions' => ['replace_head_gasket', 'replace_fuel_injector', 'scan_diagnostics', 'visual_inspection'],
    ],
    [
        'name' => 'Poor fuel economy', 'name_ar' => 'استهلاك وقود مرتفع',
        'category' => 'engine', 'system' => 'Engine management', 'subsystem' => 'Fuel delivery', 'discipline' => 'mechanical',
        'risk' => 'routine',
        'description' => 'Fuel consumption noticeably higher than normal for the vehicle.',
        'en' => [
            'syn'      => ['high fuel consumption', 'bad fuel economy', 'using more fuel', 'excessive fuel use'],
            'workshop' => ['running rich', 'heavy on fuel'],
            'customer' => ['car drinks a lot of petrol', 'using more fuel than before', 'fuel finishes quickly',
                           'petrol goes down fast'],
            'miss'     => ['fuel economey', 'poor milage'],
        ],
        'ar' => [
            'formal'   => ['استهلاك وقود مرتفع'],
            'workshop' => ['يشرب بنزين', 'صرفية البنزين عالية', 'ياكل بنزين واجد'],
        ],
        'components' => ['Oxygen sensor', 'Air filter', 'Fuel injectors', 'Tyres', 'Spark plugs'],
        'causes' => ['Faulty oxygen sensor', 'Clogged air filter', 'Under-inflated tyres',
                     'Worn spark plugs', 'Dragging brakes'],
        'inspection' => ['Scan fuel trims', 'Check tyre pressures', 'Inspect air filter', 'Check for brake drag'],
        'actions' => ['replace_air_filter', 'replace_spark_plugs', 'replace_oxygen_sensor', 'scan_diagnostics'],
    ],
];
