<?php

namespace App\Services;

use App\Exceptions\WorkflowTransitionException;
use App\Models\Maintenance;
use App\Models\MaintenanceLineItem;
use App\Models\PartInvoice;
use App\Models\PartPurchase;
use App\Models\User;
use App\Models\Vehicle;
use App\Models\VehicleLogEvent;
use Illuminate\Http\UploadedFile;
use Illuminate\Support\Carbon;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

/**
 * The SUPPLIER half of a ticket's cost — creating the parts bill, attaching the parts it covers, and
 * keeping its money honest against the paper.
 *
 * A ticket's cost comes from two independent places, and this service owns one of them:
 *
 *     supplier  →  PartInvoice        (what the part cost)      ← here
 *     garage    →  MaintenanceInvoice (what fitting it cost)    ← MaintenanceInvoiceService
 *
 * It enforces three rules the client cannot bypass:
 *
 *  1. SUPPLIER ONLY. A garage-sourced part is already billed as a line on that garage's maintenance
 *     invoice; attaching it here would double-count it on the ticket. {@see assertAttachable()} refuses it.
 *  2. ONE INVOICE PER PART. A purchase can appear on exactly one supplier bill (a foreign key, checked
 *     before a re-attach so the error names the other invoice rather than silently moving the money).
 *  3. VARIANCE GATE. If the printed total is keyed and disagrees with the attached parts by more than a
 *     cent, an explanation is mandatory — the same discipline maintenance invoices already carry.
 *
 * Attaching or detaching a purchase never touches maintenance_line_items: the invoice records what the
 * supplier charged, while the ticket cost is still generated by INSTALLING the part. Keying paper does not
 * change the ticket total, and it cannot double-count.
 */
class PartInvoiceService
{
    public function __construct(private VehicleLogService $log) {}

    /**
     * Create a supplier parts invoice and attach the purchases it covers.
     *
     * @param array{vendor_id?:?int, supplier_name?:?string, invoice_no?:?string, invoice_date?:?string,
     *              currency?:?string, tax_amount?:?float, stated_total?:?float, variance_explanation?:?string,
     *              notes?:?string, purchase_ids?:array<int>} $data
     */
    public function create(array $data, User $actor, ?UploadedFile $photo = null): PartInvoice
    {
        return DB::transaction(function () use ($data, $actor, $photo) {
            $invoice = PartInvoice::create([
                'vendor_id'        => $data['vendor_id'] ?? null,
                'supplier_name'    => $this->clean($data['supplier_name'] ?? null),
                'invoice_no'       => $this->clean($data['invoice_no'] ?? null),
                'invoice_date'     => $data['invoice_date'] ?? null,
                'currency'         => strtoupper($data['currency'] ?? 'AED'),
                'tax_amount'       => round((float) ($data['tax_amount'] ?? 0), 2),
                'discount_amount'  => round(abs((float) ($data['discount_amount'] ?? 0)), 2),
                'notes'            => $this->clean($data['notes'] ?? null),
                'recorded_by'      => $actor->id,
                'recorded_by_name' => $actor->name ?: $actor->email,
                'recorded_at'      => Carbon::now(),
            ]);

            $this->syncPurchases($invoice, $data['purchase_ids'] ?? []);
            $this->applyVarianceGate($invoice, $data);

            if ($photo) {
                [$disk, $key] = $this->storePhoto($invoice, $photo);
                $invoice->photo_disk = $disk;
                $invoice->photo_key  = $key;
            }
            $invoice->save();

            $this->logToVehicles($invoice, $actor, 'recorded');

            return $invoice->fresh(['vendor', 'purchases']);
        });
    }

    /**
     * Edit an invoice — re-key its header, replace the set of parts it covers, re-attach the photo.
     * `purchase_ids` is replace-wholesale (the editor always submits the full set), matching the way
     * MaintenanceInvoiceService treats its line items.
     */
    public function update(PartInvoice $invoice, array $data, User $actor, ?UploadedFile $photo = null): PartInvoice
    {
        return DB::transaction(function () use ($invoice, $data, $actor, $photo) {
            foreach (['vendor_id' => null, 'invoice_date' => null] as $field => $_) {
                if (array_key_exists($field, $data)) {
                    $invoice->{$field} = $data[$field] ?: null;
                }
            }
            foreach (['supplier_name', 'invoice_no', 'notes'] as $field) {
                if (array_key_exists($field, $data)) {
                    $invoice->{$field} = $this->clean($data[$field]);
                }
            }
            if (array_key_exists('currency', $data)) {
                $invoice->currency = strtoupper($data['currency'] ?: 'AED');
            }
            if (array_key_exists('tax_amount', $data)) {
                $invoice->tax_amount = round((float) ($data['tax_amount'] ?? 0), 2);
            }
            if (array_key_exists('discount_amount', $data)) {
                $invoice->discount_amount = round(abs((float) ($data['discount_amount'] ?? 0)), 2);
            }

            if (array_key_exists('purchase_ids', $data)) {
                $this->syncPurchases($invoice, $data['purchase_ids'] ?? []);
            } else {
                // Tax or discount may have moved even if the parts didn't — re-derive so the total holds.
                $invoice->recalcTotals();
            }
            $this->applyVarianceGate($invoice, $data);

            if ($photo) {
                [$disk, $key] = $this->storePhoto($invoice, $photo);
                $invoice->photo_disk = $disk;
                $invoice->photo_key  = $key;
            }
            $invoice->save();

            $this->logToVehicles($invoice, $actor, 'updated');

            return $invoice->fresh(['vendor', 'purchases']);
        });
    }

    /**
     * Delete an invoice. The PURCHASES survive — only the paper is removed, and they go back to being
     * un-invoiced buys. Deleting a document must never delete the fact that money was spent.
     */
    public function delete(PartInvoice $invoice, User $actor): void
    {
        DB::transaction(function () use ($invoice, $actor) {
            $this->logToVehicles($invoice, $actor, 'deleted');
            $invoice->purchases()->update(['part_invoice_id' => null]);
            // Same rule for the shelf lines: the STOCK stays and the movements stay — only the paper
            // goes. A receipt that loses its invoice becomes an unpapered receipt, which the
            // storehouse can show and someone can re-key; deleting the movement would delete parts
            // that are physically on a shelf.
            \App\Models\StoreMovement::where('part_invoice_id', $invoice->id)->update(['part_invoice_id' => null]);
            $invoice->delete();
        });
    }

    /**
     * Refuse to rewrite or remove a bill the business has already accepted.
     *
     * The rule itself is not new — {@see \App\Models\Concerns\IsFinancialDocument::isEditable()} has always
     * said a document stops being editable at approval, and the ledger page has always hidden its Edit and
     * Delete buttons accordingly. What was missing is that NOTHING enforced it. The endpoints took the
     * write regardless, so an approved invoice could be re-keyed, or deleted outright, by anyone holding
     * parts.purchase and a URL — including one with payments allocated against it, which would leave the
     * money pointing at a document that no longer exists.
     *
     * A hidden button is a suggestion. This is the rule.
     *
     * Called from the controller rather than from inside update() on purpose: the storehouse re-derives an
     * invoice's totals through the same service when a stock receipt lands on it, and that is a
     * recalculation of what the paper already says rather than a person editing an accepted obligation.
     */
    public function assertEditable(PartInvoice $invoice, string $action = 'changed'): void
    {
        if ($invoice->isEditable()) {
            return;
        }

        $status = $invoice->documentStatus();

        // The way out differs by where the document stands, and naming the wrong one is worse than
        // naming none: an approval can be withdrawn to reopen the paper, but a bill that has been paid
        // against cannot be — telling someone to unapprove it sends them at a button that is not there.
        $remedy = \App\Support\FinancialDocumentStatus::canMove($invoice->status, \App\Support\FinancialDocumentStatus::PENDING)
            ? ' Withdraw the approval first if it was given in error.'
            : '';

        throw new WorkflowTransitionException(
            'This invoice is ' . \App\Support\FinancialDocumentStatus::label($status)
            . ', so it can no longer be ' . $action . '. An accepted bill is corrected with an adjustment, '
            . 'not by rewriting the paper.' . $remedy,
            ['status' => $status, 'editable' => false],
        );
    }

    // ── Internals ────────────────────────────────────────────────────────────────────────────────────

    /**
     * Replace the set of purchases this invoice covers. Validates every id BEFORE writing anything, so a
     * rejected part leaves the invoice exactly as it was.
     *
     * @param array<int> $purchaseIds
     */
    private function syncPurchases(PartInvoice $invoice, array $purchaseIds): void
    {
        $ids = array_values(array_unique(array_map('intval', array_filter($purchaseIds))));

        if ($ids) {
            $purchases = PartPurchase::whereIn('id', $ids)->get();

            if ($purchases->count() !== count($ids)) {
                throw new WorkflowTransitionException(
                    'One of the selected purchases no longer exists.',
                    ['field' => 'purchase_ids'],
                );
            }

            foreach ($purchases as $purchase) {
                $this->assertAttachable($purchase, $invoice);
            }
        }

        // Release parts this invoice used to cover but that are no longer on it — and un-source the ledger
        // lines they generated, so a line never keeps pointing at a document that no longer backs it.
        $released = $invoice->purchases()->whereNotIn('id', $ids ?: [0])->pluck('maintenance_line_item_id')->filter();
        $invoice->purchases()->whereNotIn('id', $ids ?: [0])->update(['part_invoice_id' => null]);
        if ($released->isNotEmpty()) {
            MaintenanceLineItem::whereIn('id', $released)->update(['source_type' => null, 'source_id' => null]);
        }

        if ($ids) {
            PartPurchase::whereIn('id', $ids)->update(['part_invoice_id' => $invoice->id]);

            // Attaching the paper is what makes the spend auditable, so it is also what fills in the
            // structured origin on the line the purchase already generated at install time.
            $lineIds = PartPurchase::whereIn('id', $ids)->pluck('maintenance_line_item_id')->filter();
            if ($lineIds->isNotEmpty()) {
                MaintenanceLineItem::whereIn('id', $lineIds)->update([
                    'source_type' => CostSourceResolver::SOURCE_SUPPLIER_INVOICE,
                    'source_id'   => $invoice->id,
                ]);
            }
        }

        $invoice->load('purchases');
        $invoice->recalcTotals();
    }

    /**
     * The two rules that keep the ticket from double-counting: a garage-sourced part never appears on a
     * supplier invoice, and a purchase belongs to at most one of them.
     */
    private function assertAttachable(PartPurchase $purchase, PartInvoice $invoice): void
    {
        if ($purchase->purchase_source === PartPurchase::SOURCE_GARAGE) {
            throw new WorkflowTransitionException(
                "“{$purchase->part_name}” came from the garage, so it is billed on that garage's maintenance "
                . 'invoice — recording it here as well would charge the ticket twice. Only supplier purchases '
                . 'belong on a parts invoice.',
                ['field' => 'purchase_ids', 'purchase_id' => $purchase->id, 'reason' => 'garage_sourced'],
            );
        }

        if ($purchase->part_invoice_id && $purchase->part_invoice_id !== $invoice->id) {
            $other = PartInvoice::find($purchase->part_invoice_id);
            $label = $other?->invoice_no ? "invoice {$other->invoice_no}" : 'another invoice';

            throw new WorkflowTransitionException(
                "“{$purchase->part_name}” is already billed on {$label}. Remove it there first.",
                ['field' => 'purchase_ids', 'purchase_id' => $purchase->id, 'reason' => 'already_invoiced'],
            );
        }
    }

    /**
     * Validate the attached parts (+ tax) against the printed total. A gap over a cent must be explained or
     * the save is rejected. Mirrors MaintenanceInvoiceService::applyReceiptGate — one discipline, both
     * kinds of paper. Sets the fields in memory; the caller saves.
     */
    private function applyVarianceGate(PartInvoice $invoice, array $data): void
    {
        if (! array_key_exists('stated_total', $data)) {
            return; // caller isn't touching the printed total — leave it alone
        }

        $stated = ($data['stated_total'] === null || $data['stated_total'] === '')
            ? null : round((float) $data['stated_total'], 2);
        $explanation = $this->clean($data['variance_explanation'] ?? null);
        $variance    = $stated !== null ? round((float) $invoice->total_amount - $stated, 2) : 0.0;

        if ($stated !== null && abs($variance) > PartInvoice::VARIANCE_TOLERANCE && $explanation === null) {
            throw new WorkflowTransitionException(
                'The parts on this invoice total ' . $invoice->currency . ' '
                . number_format((float) $invoice->total_amount, 2) . ', but the invoice says '
                . $invoice->currency . ' ' . number_format($stated, 2)
                . '. Add an explanation to record the difference.',
                ['field' => 'variance_explanation', 'variance' => $variance],
            );
        }

        $invoice->stated_total = $stated;
        $invoice->variance_explanation = ($stated !== null && abs($variance) > PartInvoice::VARIANCE_TOLERANCE)
            ? $explanation : null;
    }

    /**
     * Record the invoice on the timeline of every vehicle it touches. One supplier bill can cover parts for
     * several cars, so each affected vehicle gets its own entry — a car's history must be complete when
     * read on its own, without knowing the invoice existed.
     */
    private function logToVehicles(PartInvoice $invoice, User $actor, string $verb): void
    {
        $purchases = $invoice->relationLoaded('purchases') ? $invoice->purchases : $invoice->purchases()->get();
        $supplier  = $invoice->supplierLabel();
        $no        = $invoice->invoice_no ? " ({$invoice->invoice_no})" : '';

        foreach ($purchases->groupBy('vehicle_id') as $vehicleId => $rows) {
            if (! $vehicleId) {
                continue;
            }

            $names = $rows->pluck('part_name')->filter()->implode(', ');
            $value = round((float) $rows->sum(fn (PartPurchase $p) => $p->grossCost()), 2);

            $opts = [
                'source_tag'  => 'parts',
                'description' => "Supplier parts invoice {$verb}{$no} · {$supplier} — {$names} · "
                    . $invoice->currency . ' ' . number_format($value, 2) . " (by {$actor->name})",
                'meta' => [
                    'part_invoice_id' => $invoice->id,
                    'supplier'        => $supplier,
                    'invoice_no'      => $invoice->invoice_no,
                    'total'           => (float) $invoice->total_amount,
                    'part_count'      => $rows->count(),
                ],
            ];

            // Anchor to the ticket when the parts belong to one (keeps the ticket link), else to the car.
            $ticketId = $rows->pluck('maintenance_id')->filter()->first();
            if ($ticketId && ($ticket = Maintenance::find($ticketId))) {
                $this->log->record($ticket, VehicleLogEvent::EVENT_COST_RECORDED, $actor, $opts);
            } elseif ($vehicle = Vehicle::find((int) $vehicleId)) {
                $this->log->recordVehicle($vehicle, VehicleLogEvent::EVENT_COST_RECORDED, $actor, $opts);
            }
        }
    }

    /** Store the invoice photo on the same disk the workflow uses, returning [disk, key]. */
    private function storePhoto(PartInvoice $invoice, UploadedFile $file): array
    {
        $disk = config('filesystems.disks.s3.bucket') ? 's3' : 'public';
        $ext  = strtolower($file->getClientOriginalExtension() ?: $file->extension() ?: 'jpg');
        $key  = $file->storeAs("part-invoices/{$invoice->id}", (string) Str::uuid() . '.' . $ext, $disk);

        return $key ? [$disk, $key] : [null, null];
    }

    private function clean($value): ?string
    {
        $v = is_string($value) ? trim($value) : '';

        return $v === '' ? null : $v;
    }
}
