<?php

namespace App\Intelligence\Support;

use Illuminate\Database\Query\Builder as QueryBuilder;
use Illuminate\Database\Eloquent\Builder as EloquentBuilder;

/**
 * Keeps demo data out of every analytical surface.
 *
 * ── WHAT AND WHY ─────────────────────────────────────────────────────────────────────────────────
 * `VehicleComponentDemoSeeder` was run by hand on 2026-08-02 to populate the Vehicle Components UI
 * for testing. It wrote, in one batch:
 *
 *     part_purchases       3,475 of 3,485 rows   (10 real)
 *     vehicle_components   3,475 of 3,477 rows   (2 real)
 *     vehicle_log_events   4,544 of 6,647 rows   (~2,100 real)
 *     component_events     the matching event stream
 *
 * The rows are convincing — plausible brands, realistic prices, a warranty spread deliberately
 * designed to exercise the dashboard's 60-day window. That is exactly what makes them dangerous.
 * A Parts dashboard built on them would look complete and would be fiction, and the first time
 * anyone checked a part number against reality the platform's credibility would be gone.
 *
 * ── WHY FILTER RATHER THAN DELETE ────────────────────────────────────────────────────────────────
 * The seeder's rows are the UI's test fixtures; deleting them breaks component development. So the
 * quarantine lives at the query layer, is applied by every intelligence read, and is asserted by a
 * golden test. The seeder tags its own rows (`write_mode='seed'` on components, a MARKER string in
 * `part_purchases.notes`, and `meta` on the event stream), so the tags are what we filter on.
 */
final class SyntheticDataFilter
{
    /** The marker the demo seeder writes into part_purchases.notes and component_events.meta. */
    public const SEED_MARKER = 'VehicleComponentDemoSeeder';

    /** vehicle_components rows written by a seeder rather than by the workflow. */
    public const SEED_WRITE_MODE = 'seed';

    /** Vehicle log event types the demo seeder generates wholesale. */
    private const SEEDED_EVENT_TYPES = ['component_installed', 'component_removed'];

    /** Exclude seeded rows from a `vehicle_components` query. */
    public function components(QueryBuilder|EloquentBuilder $query, string $table = 'vehicle_components'): QueryBuilder|EloquentBuilder
    {
        return $query->where(function ($q) use ($table) {
            $q->where("{$table}.write_mode", '<>', self::SEED_WRITE_MODE)
              ->orWhereNull("{$table}.write_mode");
        });
    }

    /** Exclude seeded rows from a `part_purchases` query. */
    public function partPurchases(QueryBuilder|EloquentBuilder $query, string $table = 'part_purchases'): QueryBuilder|EloquentBuilder
    {
        return $query->where(function ($q) use ($table) {
            $q->whereNull("{$table}.notes")
              ->orWhere("{$table}.notes", 'not like', '%' . self::SEED_MARKER . '%');
        });
    }

    /**
     * Exclude seeded rows from a `vehicle_log_events` query.
     *
     * Component install/remove events are generated by the seeder in bulk. Real workflow events of
     * those types exist only where a real component row backs them, so the type filter is applied
     * together with the marker rather than instead of it.
     */
    public function vehicleLogEvents(QueryBuilder|EloquentBuilder $query, string $table = 'vehicle_log_events'): QueryBuilder|EloquentBuilder
    {
        return $query->where(function ($q) use ($table) {
            $q->whereNotIn("{$table}.event_type", self::SEEDED_EVENT_TYPES)
              ->orWhere(function ($inner) use ($table) {
                  $inner->whereNull("{$table}.meta")
                        ->orWhere("{$table}.meta", 'not like', '%' . self::SEED_MARKER . '%');
              });
        });
    }

    /** Exclude seeded rows from a `component_events` query. */
    public function componentEvents(QueryBuilder|EloquentBuilder $query, string $table = 'component_events'): QueryBuilder|EloquentBuilder
    {
        return $query->where(function ($q) use ($table) {
            $q->whereNull("{$table}.meta")
              ->orWhere("{$table}.meta", 'not like', '%' . self::SEED_MARKER . '%');
        });
    }
}
