<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

/**
 * Fleet Maintenance Workflow — Phase 1 schema bridge.
 *
 * Adds the app-driven TICKET LIFECYCLE on top of the existing `maintenances` row, replacing
 * the WhatsApp relay between the Inspector (Abu Maroof) → Logistics → Controllers. A workflow
 * ticket IS a hand-entered workshop event (origin = 'manual'); these columns layer a role-driven
 * state machine and its captured-at-handoff data over that row.
 *
 * `workflow_status` is deliberately SEPARATE from the sheet-derived `event_status` (OUT/IN/…):
 * the service maps one onto the other (in_transit…ready → 'OUT' so the car reads "in garage";
 * closed → 'IN' so it's freed) so the existing board, SLA and operational_status cascade keep
 * working untouched. Every column is nullable and additive — legacy rows (sheet log, contract
 * headers) are completely unaffected and existing reports keep reading exactly what they did.
 */
return new class extends Migration
{
    public function up(): void
    {
        Schema::table('maintenances', function (Blueprint $table) {
            // The lifecycle state (UC-1 … UC-6). Null = not a workflow ticket (legacy/sheet/header rows).
            $table->string('workflow_status', 30)->nullable()->after('event_status')->index();

            // Why the ticket exists: 'periodic' (planned service) or 'customer_reported' (a fault).
            // 'periodic' is mapped to visit_context = 'routine' so foresight ignores planned service.
            $table->string('trigger_reason', 30)->nullable()->after('workflow_status');

            // The customer's reported issue (free text) — only for customer_reported tickets.
            $table->text('customer_complaint')->nullable()->after('trigger_reason');

            // Abu Maroof's structured test-drive report: {symptoms[], severity, recommended_action, notes}.
            $table->json('test_drive_report')->nullable()->after('customer_complaint');

            // Odometer the Logistics team captures at the garage handoff (photo lives in inspection_records).
            $table->unsignedInteger('dispatch_odometer')->nullable()->after('test_drive_report');

            // Feedback the Logistics team relays from the garage (ETA, found issues, "ready").
            $table->text('garage_feedback')->nullable()->after('dispatch_odometer');

            // Role-stamped handoffs — WHO advanced the ticket and WHEN. Generated by the service,
            // never hand-typed: this is the audit trail that makes the spreadsheet obsolete.
            $table->foreignId('inspected_by')->nullable()->after('garage_feedback')->constrained('users')->nullOnDelete();
            $table->timestamp('inspected_at')->nullable()->after('inspected_by');

            $table->foreignId('dispatched_by')->nullable()->after('inspected_at')->constrained('users')->nullOnDelete();
            $table->timestamp('dispatched_at')->nullable()->after('dispatched_by');

            $table->foreignId('repair_started_by')->nullable()->after('dispatched_at')->constrained('users')->nullOnDelete();
            $table->timestamp('repair_started_at')->nullable()->after('repair_started_by');

            $table->foreignId('ready_by')->nullable()->after('repair_started_at')->constrained('users')->nullOnDelete();
            $table->timestamp('ready_at')->nullable()->after('ready_by');

            $table->foreignId('wf_closed_by')->nullable()->after('ready_at')->constrained('users')->nullOnDelete();
            $table->timestamp('wf_closed_at')->nullable()->after('wf_closed_by');
        });
    }

    public function down(): void
    {
        Schema::table('maintenances', function (Blueprint $table) {
            $table->dropConstrainedForeignKey('inspected_by');
            $table->dropConstrainedForeignKey('dispatched_by');
            $table->dropConstrainedForeignKey('repair_started_by');
            $table->dropConstrainedForeignKey('ready_by');
            $table->dropConstrainedForeignKey('wf_closed_by');

            $table->dropColumn([
                'workflow_status',
                'trigger_reason',
                'customer_complaint',
                'test_drive_report',
                'dispatch_odometer',
                'garage_feedback',
                'inspected_at',
                'dispatched_at',
                'repair_started_at',
                'ready_at',
                'wf_closed_at',
            ]);
        });
    }
};
