<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

/**
 * Two changes that turn traceability from something DERIVED into something QUERYABLE.
 *
 * ── 1. Structured origin on every amount ────────────────────────────────────────────────────────────
 * Until now, "which document backs this line?" was answered by reverse-looking-up four tables at read
 * time. That is correct but it is not reportable: a question like "how much did we spend on brakes this
 * year, and how much of it is documented?" would need the resolver to run over every line in the fleet.
 *
 * So the answer is denormalised onto the line itself as (source_type, source_id), written at the moment
 * the line is created and updated when a purchase is later attached to an invoice. The hierarchy the
 * business cares about becomes a plain SQL join:
 *
 *     ticket → fault (maintenance_task_id) → line (category_key, kind)
 *            → origin (source_type, source_id) → the document
 *
 * The resolver keeps its derivation logic as the source of truth for CORRECTNESS — the column is a cache
 * of it, and `cost:trace-audit` re-derives rather than trusting the cache, so a stale value is caught
 * rather than believed.
 *
 * ── 2. Legacy marking, without faking history ───────────────────────────────────────────────────────
 * 173,934 AED of existing ticket cost has no document and never will — it was recorded before the
 * documents existed. Inventing invoices for it would be far worse than admitting it, so instead every
 * cost that predates this rollout is stamped `cost_legacy_at`. That separates two things which look
 * identical in a total but are completely different in meaning:
 *
 *     LEGACY UNVERIFIED — recorded before the rules existed. Known, bounded, and shrinking as it is
 *                         migrated. Not anyone's fault.
 *     UNVERIFIED        — recorded AFTER the rules existed, with no document. Should be impossible now
 *                         (the closure gate refuses it) and is a genuine problem if it appears.
 *
 * Management then gets a real progress metric — verified vs legacy — instead of a permanent 0%.
 */
return new class extends Migration
{
    public function up(): void
    {
        Schema::table('maintenance_line_items', function (Blueprint $table) {
            // Which of the four documents backs this amount. Mirrors CostSourceResolver's vocabulary.
            $table->string('source_type', 24)->nullable()->after('entry_source');
            $table->unsignedBigInteger('source_id')->nullable()->after('source_type');

            // The reporting index: spend by origin, by category, over a period.
            $table->index(['source_type', 'source_id']);
            $table->index(['category_key', 'kind']);
        });

        // Backfill from the relations that already encode the answer. Deliberately conservative: a line
        // that cannot be attributed is left NULL rather than guessed at — a wrong origin would be worse
        // than an absent one, because it would look audited.
        $this->backfillOrigins();

        Schema::table('maintenances', function (Blueprint $table) {
            // When this ticket's cost was accepted as legacy (pre-document-era). Null = held to the
            // current rules. A timestamp rather than a boolean so the migration itself is auditable.
            $table->timestamp('cost_legacy_at')->nullable()->after('cost_recorded_by');
            $table->string('cost_legacy_note')->nullable()->after('cost_legacy_at');
            $table->index('cost_legacy_at');
        });

        // Every ticket that already carries cost predates the document rules — stamp it as legacy so it
        // is reported as a known, shrinking backlog rather than as a fresh failure.
        DB::table('maintenances')
            ->whereNotNull('cost')
            ->where('cost', '>', 0)
            ->update([
                'cost_legacy_at'   => now(),
                'cost_legacy_note' => 'Recorded before financial documents were introduced (2026-08-04).',
            ]);
    }

    /**
     * Point every existing line at the document behind it, using the links that already exist. Runs in
     * four targeted statements rather than row-by-row so it stays fast on a large ledger.
     */
    private function backfillOrigins(): void
    {
        // A line generated by a part purchase whose supplier invoice is on file.
        DB::statement("
            UPDATE maintenance_line_items li
            JOIN part_purchases p ON p.maintenance_line_item_id = li.id
            SET li.source_type = 'supplier_invoice', li.source_id = p.part_invoice_id
            WHERE p.part_invoice_id IS NOT NULL
        ");

        // A credit line written by a return.
        DB::statement("
            UPDATE maintenance_line_items li
            JOIN part_returns r ON r.credit_line_item_id = li.id
            SET li.source_type = 'credit_note', li.source_id = r.id
        ");

        // A line written by an approved adjustment.
        DB::statement("
            UPDATE maintenance_line_items li
            JOIN cost_adjustments a ON a.line_item_id = li.id
            SET li.source_type = 'adjustment', li.source_id = a.id
        ");

        // Anything billed on a garage invoice and not already claimed above.
        DB::statement("
            UPDATE maintenance_line_items li
            SET li.source_type = 'garage_invoice', li.source_id = li.maintenance_invoice_id
            WHERE li.maintenance_invoice_id IS NOT NULL AND li.source_type IS NULL
        ");
    }

    public function down(): void
    {
        Schema::table('maintenance_line_items', function (Blueprint $table) {
            $table->dropIndex(['source_type', 'source_id']);
            $table->dropIndex(['category_key', 'kind']);
            $table->dropColumn(['source_type', 'source_id']);
        });

        Schema::table('maintenances', function (Blueprint $table) {
            $table->dropIndex(['cost_legacy_at']);
            $table->dropColumn(['cost_legacy_at', 'cost_legacy_note']);
        });
    }
};
